name: Deploy Mystery Message App

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install

            - name: Prepare EC2 folder
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      rm -rf /home/ubuntu/mystery-message
                      mkdir -p /home/ubuntu/mystery-message

            - name: Upload project using rsync
              uses: burnett01/rsync-deployments@5.1
              with:
                  switches: -avzr --delete
                  path: ./
                  remote_path: /home/ubuntu/mystery-message
                  remote_host: ${{ secrets.EC2_HOST }}
                  remote_user: ${{ secrets.EC2_USERNAME }}
                  remote_key: ${{ secrets.EC2_SSH_KEY }}

            - name: SSH into EC2 and restart app
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd /home/ubuntu/mystery-message
                      npm install
                      pm2 restart next-app || pm2 start npm --name "next-app" -- run dev
